services:
    Alengo\Bundle\AlengoWebspaceSettingsBundle\Controller\Admin\WebspaceSettingsController:
        public: 'true'
        arguments:
            - '@fos_rest.view_handler.default'
            - '@security.token_storage'
            - '@doctrine.orm.default_entity_manager'
            - '@request_stack'
            - '@event_dispatcher'
            - '%alengo_webspace_settings.type_select%'
