services:
    Alengo\Bundle\AlengoWebspaceSettingsBundle\Controller\Admin\WebspaceSettingsController:
        public: 'true'
        arguments:
            - '@fos_rest.view_handler.default'
            - '@doctrine.orm.default_entity_manager'
            - '@request_stack'
