services:
    Alengo\Bundle\AlengoWebspaceSettingsBundle\Admin\WebspaceSettingsAdmin:
        arguments:
            - '@sulu_core.webspace.webspace_manager'
            - '@sulu_admin.view_builder_factory'
            - '@sulu_security.security_checker'
        tags:
            - { name: 'sulu.admin' }
            - { name: 'sulu.context', context: 'admin' }

    Alengo\Bundle\AlengoWebspaceSettingsBundle\Repository\WebspaceSettingsRepository:
        public: 'true'
        arguments:
            - '@doctrine'
        tags:
            - 'doctrine.repository_service'

    Alengo\Bundle\AlengoWebspaceSettingsBundle\Twig\WebspaceSettingsExtension:
        public: 'true'
        arguments:
            - '@request_stack'
            - '@alengo_webspace_settings.repository.webspace_settings'
        tags:
            - { name: twig.extension }

    alengo_webspace_settings.repository.webspace_settings:
        alias: Alengo\Bundle\AlengoWebspaceSettingsBundle\Repository\WebspaceSettingsRepository

    alengo_webspace_settings.trash_item_handler.webspace_settings:
        class: Alengo\Bundle\AlengoWebspaceSettingsBundle\Trash\WebsiteSettingsTrashItemHandler
        arguments:
            - '@sulu_trash.trash_item_repository'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: 'sulu_trash.store_trash_item_handler' }
            - { name: 'sulu_trash.restore_trash_item_handler' }
            - { name: 'sulu_trash.restore_configuration_provider' }

    alengo_webspace_settings.webspace_settings_trash_subscriber:
        class: Alengo\Bundle\AlengoWebspaceSettingsBundle\EventSubscriber\WebspaceSettingsTrashSubscriber
        arguments:
            - '@sulu_trash.trash_manager'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: 'kernel.event_subscriber' }

    Alengo\Bundle\AlengoWebspaceSettingsBundle\Content\Select\TypeSelect:
        arguments:
            - '@Symfony\Contracts\Translation\TranslatorInterface'
            - '%alengo_webspace_settings.type_select%'
        public: 'true'

    alengo_webspace_settings.content.select.type_select:
        alias: Alengo\Bundle\AlengoWebspaceSettingsBundle\Content\Select\TypeSelect
        public: 'true'